spring:
  data:
    mongodb:
      authentication-database: admin
      database: notification
      host: localhost
      password: janis
      port: 27017
      username: janis
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping:
          orderConfirmation: com.janis.order.kafka.OrderConfirmation
          paymentConfirmation: com.janis.payment.notification.PaymentNotificationRequest
      group-id: paymentGroup, orderGroup
      auto-offset-reset: earliest
  mail:
    host: localhost
    port: 1025
    username: janis
    password: janis
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 3000
        timeout: 3000
        writeTimeout: 3000
server:
  port: 8040